create table public.segment (
  id bigint generated by default as identity not null,
  speaker text null,
  start real null,
  "end" real null,
  text text null,
  embedding public.vector null,
  constraint segment_pkey primary key (id)
) TABLESPACE pg_default;